name: serinus_swagger
description: A Serinus plugin to generate OpenAPI documentation from your Serinus app.
version: 1.0.1
repository: https://github.com/serinus-nest/serinus_swagger
homepage: https://docs.serinus.app/plugins/swagger
documentation: https://docs.serinus.app/plugins/swagger

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  serinus: ^0.5.0
  yaml_writer: ^2.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
