openapi: '3.0.0'
info: 
  title: 'Serinus Test Swagger'
  version: '1.0'
  description: 'API documentation for the Serinus project'
paths: 
  /: 
    get: 
      tags: 
        - 'AppController'
      responses: 
        200: 
          description: 'Hello world response'
          content: 
            text/plain: 
              type: 'text/plain'
              schema: 
                type: 'string'
                example: 'Post route'
    parameters: 
      - name: 'name'
        in: 'query'
        required: false
        deprecated: false
        description: null
        allowEmptyValue: false
  /post/{data}: 
    post: 
      tags: 
        - 'AppController'
      requestBody: 
        required: false
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/User'
      responses: 
        200: 
          description: 'Post response'
          content: 
            application/json: 
              type: 'application/json'
              schema: 
                $ref: '#/components/schemas/User'
            text/plain: 
              type: 'text/plain'
              schema: 
                type: 'string'
                example: 'Post route'
    parameters: 
      - name: 'data'
        in: 'path'
        required: true
        deprecated: false
        description: null
        allowEmptyValue: false
  /a/: 
    get: 
      tags: 
        - 'App2Controller'
      responses: 
        200: 
          description: 'Hello world response'
          content: 
            text/plain: 
              type: 'text/plain'
              schema: 
                type: 'string'
                example: 'Post route'
    parameters: 
      - name: 'name'
        in: 'query'
        required: false
        deprecated: false
        description: null
        allowEmptyValue: false
  /a/post: 
    post: 
      tags: 
        - 'App2Controller'
      requestBody: 
        required: false
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/User'
      responses: 
        200: 
          description: 'Post response'
          content: 
            application/json: 
              type: 'application/json'
              schema: 
                $ref: '#/components/schemas/User'
            text/plain: 
              type: 'text/plain'
              schema: 
                type: 'string'
                example: 'Post route'
    parameters: []
components: 
  schemas: 
    User: 
      type: 'object'
      properties: 
        name: 
          type: 'string'
        age: 
          type: 'integer'
        email: 
          type: 'string'
